---
- name: Change our index.html content and restart and enable web services
  hosts: all
  gather_facts: true
  tasks:
    - name: Modify content in /var/www/html/index.html content
      ansible.builtin.copy:
        src: files/index.html
        dest: /var/www/html/index.html
        mode: '0644'
      notify: Restart services

  handlers:
    - name: Restart services
      ansible.builtin.service:
        name: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"
        state: restarted
        enabled: true
