---

- hosts: all
  become: true
  tasks:

  - name: remove apache2 and php package for both ubuntu and centos server
    package:
      name:
        - "{{ apache_package }}"
        - "{{php_package }}"
      state: absent
      update_cache: yes

